[package]
name = "http"
version = "0.1.0"
authors = ["vkstrm <mongomoves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"
url = "2.2.2"
clap = "3.0.0-beta.2"
serde_json = "1.0.68"
serde = {version = "1.0.130", features = ["derive"] }